// Edit this file to add or modify conferences.
// Each entry needs: name, specialty, year, startDate, endDate, city, country, lat, lng, url, organizer, description.
// Dates in YYYY-MM-DD format. Lat/lng are decimal degrees.

const CONFERENCES = [
  {
    name: "International Surgical Week (ISW 2026) — 51st World Congress of ISS/SIC",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-19",
    endDate: "2026-04-23",
    city: "Mexico City",
    country: "Mexico",
    lat: 19.4326,
    lng: -99.1332,
    url: "https://www.isw2026.org/",
    organizer: "International Society of Surgery (ISS/SIC)",
    description: "The 51st World Congress of the International Society of Surgery, the flagship global gathering for general surgeons."
  },
  {
    name: "ACS Clinical Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-26",
    endDate: "2026-09-29",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/clinical-congress-2026/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons, covering all surgical specialties."
  },
  {
    name: "European Surgery Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-17",
    endDate: "2026-08-19",
    city: "Paris",
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    url: "https://www.eurosurgerycongress.org/",
    organizer: "European Surgery Congress",
    description: "Major European general surgery congress."
  },
  {
    name: "34th International EAES Congress",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-23",
    endDate: "2026-06-26",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://eaes.eu/eaes-annual-congress/",
    organizer: "European Association for Endoscopic Surgery",
    description: "Annual congress focused on endoscopic, laparoscopic and minimally invasive surgery."
  },
  {
    name: "19th International Conference & Expo on Surgery and Surgeons",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-25",
    endDate: "2026-08-26",
    city: "Rome",
    country: "Italy",
    lat: 41.9028,
    lng: 12.4964,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "International conference covering advances across surgical specialties."
  },
  {
    name: "Global Conference on Surgery and Anaesthesia (7th Edition)",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-24",
    endDate: "2026-09-26",
    city: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lng: -0.1278,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "Hybrid international conference on surgery and anaesthesia."
  },
  {
    name: "Surgery 2026 — 4th International Conference on Surgery and Anesthesia",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-26",
    endDate: "2026-11-27",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "Hybrid event covering surgical and anesthesia advances."
  },
  {
    name: "22nd Annual Academic Surgical Congress",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-02-09",
    endDate: "2027-02-11",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.academicsurgicalcongress.org/",
    organizer: "Association for Academic Surgery / Society of University Surgeons",
    description: "Joint annual academic surgery meeting featuring leading-edge surgical research."
  },
  {
    name: "EAES Annual Congress 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-06-15",
    endDate: "2027-06-18",
    city: "Düsseldorf",
    country: "Germany",
    lat: 51.2277,
    lng: 6.7735,
    url: "https://eaes.eu/eaes-annual-congress/",
    organizer: "European Association for Endoscopic Surgery",
    description: "Annual European endoscopic surgery congress."
  },
  {
    name: "62nd STS Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-01-30",
    endDate: "2026-02-02",
    city: "New Orleans",
    country: "USA",
    lat: 29.9511,
    lng: -90.0715,
    url: "https://www.sts.org/calendar-of-events/62nd-sts-annual-meeting",
    organizer: "Society of Thoracic Surgeons",
    description: "Premier meeting for cardiothoracic surgeons in North America."
  },
  {
    name: "AATS 106th Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-05-02",
    endDate: "2026-05-05",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://events.aats.org/am26",
    organizer: "American Association for Thoracic Surgery",
    description: "Flagship meeting of the AATS at McCormick Place, Chicago."
  },
  {
    name: "EACTS Annual Meeting 2026",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-10-07",
    endDate: "2026-10-10",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://www.eacts.org/",
    organizer: "European Association for Cardio-Thoracic Surgery",
    description: "Europe's leading cardiothoracic surgery congress."
  },
  {
    name: "34th ESTS Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-06-07",
    endDate: "2026-06-09",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://estsmeeting.com/",
    organizer: "European Society of Thoracic Surgeons",
    description: "Annual meeting of the European Society of Thoracic Surgeons."
  },
  {
    name: "EACTS / STS / LACES Latin America Cardiovascular Surgery Conference",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-03-01",
    endDate: "2026-03-03",
    city: "Santiago",
    country: "Chile",
    lat: -33.4489,
    lng: -70.6693,
    url: "https://www.sts.org/calendar-of-events/2026-stseactslaces-latin-america-cardiovascular-surgery-conference",
    organizer: "EACTS / STS / LACES",
    description: "Joint Latin America cardiovascular surgery conference."
  },
  {
    name: "2026 CNS Annual Meeting",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-10-31",
    endDate: "2026-11-04",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.cns.org/annualmeeting",
    organizer: "Congress of Neurological Surgeons",
    description: "Premier annual meeting for neurosurgeons in the United States."
  },
  {
    name: "WFNS 5th International Neurosurgery and Neurological Surgeons Conference",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-01-14",
    endDate: "2026-01-16",
    city: "Dubai",
    country: "United Arab Emirates",
    lat: 25.2048,
    lng: 55.2708,
    url: "https://wfns.org/events/17/wfns-member-societies/329/5th-international-neurosurgery-and-neurological-surgeons-conference",
    organizer: "World Federation of Neurosurgical Societies",
    description: "International neurosurgery conference under WFNS member societies."
  },
  {
    name: "2027 CNS Annual Meeting",
    specialty: "Neurosurgery",
    year: 2027,
    startDate: "2027-10-23",
    endDate: "2027-10-27",
    city: "Phoenix",
    country: "USA",
    lat: 33.4484,
    lng: -112.0740,
    url: "https://www.cns.org/meetings/past-and-future-annual-meetings",
    organizer: "Congress of Neurological Surgeons",
    description: "Annual meeting of the Congress of Neurological Surgeons."
  },
  {
    name: "AANS 2027 Annual Scientific Meeting",
    specialty: "Neurosurgery",
    year: 2027,
    startDate: "2027-04-09",
    endDate: "2027-04-12",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://annualmeeting.aans.org/",
    organizer: "American Association of Neurological Surgeons",
    description: "Annual scientific meeting of the AANS."
  },
  {
    name: "AAOS 2026 Annual Meeting",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-03-02",
    endDate: "2026-03-06",
    city: "New Orleans",
    country: "USA",
    lat: 29.9511,
    lng: -90.0715,
    url: "https://aaos2026.org/",
    organizer: "American Academy of Orthopaedic Surgeons",
    description: "Largest orthopaedic surgery meeting in the world."
  },
  {
    name: "EFORT Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-05-04",
    endDate: "2026-05-06",
    city: "Málaga",
    country: "Spain",
    lat: 36.7213,
    lng: -4.4214,
    url: "https://www.efort.org/events-calendar/orthopaedic-event-calendar/",
    organizer: "European Federation of National Associations of Orthopaedics and Traumatology",
    description: "Annual European orthopaedics and traumatology congress."
  },
  {
    name: "SICOT 2026 Orthopaedic World Congress",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-09-29",
    endDate: "2026-10-01",
    city: "Kyoto",
    country: "Japan",
    lat: 35.0116,
    lng: 135.7681,
    url: "https://www.sicot.org/international-events-calendar",
    organizer: "Société Internationale de Chirurgie Orthopédique et de Traumatologie",
    description: "International orthopaedic and trauma surgery world congress."
  },
  {
    name: "Scoliosis Research Society Asia Pacific Meeting 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-02-06",
    endDate: "2026-02-07",
    city: "Fukuoka",
    country: "Japan",
    lat: 33.5902,
    lng: 130.4017,
    url: "https://www.srs.org/Meetings-Conferences/Regional-Scientific-Meeting/RSM-2026",
    organizer: "Scoliosis Research Society",
    description: "Regional meeting focused on spine deformity surgery."
  },
  {
    name: "ASPS Plastic Surgery The Meeting 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-10-15",
    endDate: "2026-10-18",
    city: "Houston",
    country: "USA",
    lat: 29.7604,
    lng: -95.3698,
    url: "https://www.plasticsurgerythemeeting.com/",
    organizer: "American Society of Plastic Surgeons",
    description: "Largest annual plastic surgery meeting in the United States."
  },
  {
    name: "ISAPS Body Masters 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-07-03",
    endDate: "2026-07-05",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://www.isaps.org/education/events/events-calendar/",
    organizer: "International Society of Aesthetic Plastic Surgery",
    description: "International course on aesthetic body contouring surgery."
  },
  {
    name: "Aesthetic MEET 2026 (ASAPS)",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-05-14",
    endDate: "2026-05-17",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.theaestheticmeeting.com/",
    organizer: "American Society for Aesthetic Plastic Surgery",
    description: "Annual meeting of the Aesthetic Society."
  },
  {
    name: "2026 Asian Pacific Plastic Surgery & Craniofacial Congress",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-11-12",
    endDate: "2026-11-14",
    city: "Bangkok",
    country: "Thailand",
    lat: 13.7563,
    lng: 100.5018,
    url: "https://apc2026.org/",
    organizer: "Asian Pacific Plastic Surgery Association",
    description: "Regional Asia-Pacific congress for plastic and craniofacial surgery."
  },
  {
    name: "XXIX IFSO World Congress 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-09-01",
    endDate: "2026-09-04",
    city: "Toronto",
    country: "Canada",
    lat: 43.6532,
    lng: -79.3832,
    url: "https://ifso2026.org/",
    organizer: "International Federation for the Surgery of Obesity and Metabolic Disorders",
    description: "World congress on bariatric and metabolic surgery."
  },
  {
    name: "IFSO-EC Congress 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-08",
    city: "Málaga",
    country: "Spain",
    lat: 36.7213,
    lng: -4.4214,
    url: "https://www.ifso-ec.com/",
    organizer: "IFSO European Chapter",
    description: "European chapter congress on bariatric and metabolic surgery."
  },
  {
    name: "Joint IFSO-EC / EASO Congress 2027",
    specialty: "Bariatric Surgery",
    year: 2027,
    startDate: "2027-05-12",
    endDate: "2027-05-14",
    city: "Munich",
    country: "Germany",
    lat: 48.1351,
    lng: 11.5820,
    url: "https://www.ifso-ec.com/",
    organizer: "IFSO-EC / EASO",
    description: "Joint European bariatric / obesity congress."
  },
  {
    name: "APTS 2026 & SOHNSS ENT Congress",
    specialty: "Endocrine / ENT Surgery",
    year: 2026,
    startDate: "2026-04-09",
    endDate: "2026-04-12",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    url: "https://asean-endocrinejournal.org/index.php/JAFES/announcement/view/289",
    organizer: "Asia-Pacific Society of Thyroid Surgery",
    description: "Joint Asia-Pacific congress on thyroid and head & neck surgery."
  },
  {
    name: "Mayo Clinic Interactive Surgery Symposium 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-01",
    endDate: "2026-02-06",
    city: "Kapalua, Maui",
    country: "USA",
    lat: 20.9988,
    lng: -156.6678,
    url: "https://ce.mayo.edu/surgical-specialties/content/mayo-clinic-interactive-surgery-symposium-2026",
    organizer: "Mayo Clinic School of Continuous Professional Development",
    description: "General surgery CME symposium at The Ritz-Carlton Kapalua covering everyday surgical practice updates."
  },
  {
    name: "Mayo Clinic Advancements in Surgical & Medical Management of the Spine",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-02-22",
    endDate: "2026-02-26",
    city: "Lahaina, Maui",
    country: "USA",
    lat: 20.8783,
    lng: -156.6825,
    url: "https://ce.mayo.edu/",
    organizer: "Mayo Clinic School of Continuous Professional Development",
    description: "Spine surgery CME held at the Hyatt Regency Maui Resort and Spa, covering surgical and medical spine management."
  },
  {
    name: "Orthopedics Today Hawaii 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-01-10",
    endDate: "2027-01-14",
    city: "Wailea, Maui",
    country: "USA",
    lat: 20.6843,
    lng: -156.4416,
    url: "https://www.healio.com/meeting/othawaii/home",
    organizer: "Healio LIVE",
    description: "20th-anniversary orthopaedic CME conference at Grand Wailea covering sports medicine, arthroplasty, trauma, and practice management."
  },
  {
    name: "66th Annual Conference of the West African College of Surgeons (WACS)",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-08",
    endDate: "2026-02-12",
    city: "Accra",
    country: "Ghana",
    lat: 5.6037,
    lng: -0.1870,
    url: "https://66thwacs2026agsm.org/",
    organizer: "West African College of Surgeons",
    description: "Annual general meeting of WACS focused on building West African surgical capacity, held at the University of Professional Studies."
  },
  {
    name: "RACS 94th Annual Scientific Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-30",
    endDate: "2026-05-03",
    city: "Perth",
    country: "Australia",
    lat: -31.9523,
    lng: 115.8613,
    url: "https://www.surgeons.org/conferences-events/college-calendar-of-events/RACS-94th-Annual-Scientific-Congress-2026",
    organizer: "Royal Australasian College of Surgeons",
    description: "Annual scientific congress of the RACS at the Perth Convention and Exhibition Centre."
  },
  {
    name: "SVS Vascular Annual Meeting (VAM) 2026",
    specialty: "Vascular Surgery",
    year: 2026,
    startDate: "2026-06-10",
    endDate: "2026-06-13",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://vascular.org/vascular-specialists/education-and-meetings/meetings/2026-vascular-annual-meeting",
    organizer: "Society for Vascular Surgery",
    description: "Premier annual meeting for vascular surgeons in North America."
  },
  {
    name: "ESVS 40th Annual Meeting 2026",
    specialty: "Vascular Surgery",
    year: 2026,
    startDate: "2026-10-06",
    endDate: "2026-10-09",
    city: "Belgrade",
    country: "Serbia",
    lat: 44.7866,
    lng: 20.4489,
    url: "https://esvs.org/event/esvs-40th-annual-meeting/",
    organizer: "European Society for Vascular Surgery",
    description: "40th annual meeting of Europe's vascular surgery society."
  },
  {
    name: "XXVI Ibero-Latin American Congress of Plastic Surgery — FILACP Panama 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-04-21",
    endDate: "2026-04-24",
    city: "Panama City",
    country: "Panama",
    lat: 8.9824,
    lng: -79.5199,
    url: "https://www.filacppanama2026.com/",
    organizer: "FILACP & Panamanian Association of Plastic, Aesthetic and Reconstructive Surgery",
    description: "Biennial Ibero-Latin American plastic surgery congress at the Panama Convention Center."
  },
  {
    name: "55° Congreso Argentino de Cirugía Plástica, Estética y Reparadora (SACPER)",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-10-21",
    endDate: "2026-10-23",
    city: "Rosario",
    country: "Argentina",
    lat: -32.9442,
    lng: -60.6505,
    url: "https://congresosacper2026.com/",
    organizer: "Sociedad Argentina de Cirugía Plástica (SACPER)",
    description: "55th Argentine congress of plastic, aesthetic and reconstructive surgery at City Center Rosario."
  },
  {
    name: "96° Congreso Argentino de Cirugía",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-02",
    endDate: "2026-11-04",
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.6037,
    lng: -58.3816,
    url: "https://aac.org.ar/96congreso/",
    organizer: "Asociación Argentina de Cirugía (AAC)",
    description: "Argentina's flagship surgery congress at Hotel Hilton Buenos Aires, alongside thoracic, coloproctology, plastic, trauma and breast sub-congresses."
  },
  {
    name: "L Congreso Internacional de Cirugía General (AMCG) 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-10-25",
    endDate: "2026-10-30",
    city: "Veracruz",
    country: "Mexico",
    lat: 19.1738,
    lng: -96.1342,
    url: "https://www.amcg2026.mx/",
    organizer: "Asociación Mexicana de Cirujanos Generales (AMCG)",
    description: "50th international congress of Mexican general surgeons, held at WTC Veracruz."
  },
  {
    name: "XXXII International Congress of Surgery — El Salvador 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-23",
    endDate: "2026-03-27",
    city: "San Salvador",
    country: "El Salvador",
    lat: 13.6929,
    lng: -89.2182,
    url: "https://congresocirugia2026.com/",
    organizer: "Asociación Salvadoreña de Cirugía General",
    description: "Salvadoran general surgery international congress at Hotel Hilton San Salvador, featuring 22 international speakers."
  },
  {
    name: "Endo 2026 — 5th World Congress of GI Endoscopy",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-24",
    endDate: "2026-09-26",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://www.surgeon.co.za/events/endo-2026-world-congress/",
    organizer: "Association of Surgeons of South Africa (ASSA)",
    description: "5th World Congress of GI Endoscopy hosted by ASSA in Cape Town."
  },
  {
    name: "SAOA 72nd Annual Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-08-31",
    endDate: "2026-09-03",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Orthopaedic Association (SAOA)",
    description: "Annual congress of the SAOA held at Century City, Cape Town."
  },
  {
    name: "27th SAAS Biennial Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-08",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://arthroplastysociety.org.za/saas-congress-2026/",
    organizer: "South African Arthroplasty Society (SAAS)",
    description: "27th biennial congress of the South African Arthroplasty Society, focused on joint replacement surgery."
  },
  {
    name: "SAOA 73rd Annual Congress 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-09-06",
    endDate: "2027-09-09",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Orthopaedic Association (SAOA)",
    description: "Annual SAOA congress in Century City, Cape Town."
  },
  {
    name: "SASS Spine Congress 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-05-06",
    endDate: "2027-05-08",
    city: "Johannesburg",
    country: "South Africa",
    lat: -26.2041,
    lng: 28.0473,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Spine Society (SASS)",
    description: "Annual congress of the South African Spine Society at Sandton Convention Centre."
  },
  {
    name: "126th Annual Congress of the Japan Surgical Society",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-23",
    endDate: "2026-04-25",
    city: "Sapporo",
    country: "Japan",
    lat: 43.0642,
    lng: 141.3469,
    url: "https://jp.jssoc.or.jp/jss126/en/",
    organizer: "Japan Surgical Society (JSS)",
    description: "Japan's largest annual surgical congress, hosted by Hokkaido University."
  },
  {
    name: "127th Annual Congress of the Japan Surgical Society",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-04-08",
    endDate: "2027-04-10",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6762,
    lng: 139.6503,
    url: "https://jp.jssoc.or.jp/modules/en/",
    organizer: "Japan Surgical Society (JSS)",
    description: "Annual congress of the Japan Surgical Society, hosted by Tokyo Medical University."
  },
  {
    name: "ASICON 2026 — 86th Annual Conference of the Association of Surgeons of India",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-12-17",
    endDate: "2026-12-19",
    city: "Ahmedabad",
    country: "India",
    lat: 23.0225,
    lng: 72.5714,
    url: "https://asicon26.com/",
    organizer: "Association of Surgeons of India (ASI)",
    description: "India's flagship surgical congress at the Gujarat University Convention & Exhibition Centre."
  },
  {
    name: "KSERS 2026 — 58th Korean Society of Endo-Laparoscopic & Robotic Surgery Congress",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-23",
    endDate: "2026-04-25",
    city: "Seoul",
    country: "South Korea",
    lat: 37.5665,
    lng: 126.9780,
    url: "https://ksers.org/",
    organizer: "Korean Society of Endo-Laparoscopic & Robotic Surgery",
    description: "Korean congress focused on endoscopic, laparoscopic, and robotic surgery."
  },
  {
    name: "AUA 2026 — 121st Annual Meeting of the American Urological Association",
    specialty: "Urology",
    year: 2026,
    startDate: "2026-05-15",
    endDate: "2026-05-18",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.auanet.org/AUA2026",
    organizer: "American Urological Association",
    description: "Largest annual urology meeting in North America, at Walter E. Washington Convention Center."
  },
  {
    name: "AUA 2027 — 122nd Annual Meeting of the American Urological Association",
    specialty: "Urology",
    year: 2027,
    startDate: "2027-05-21",
    endDate: "2027-05-24",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://www.auanet.org/AUA2027/for-exhibitors",
    organizer: "American Urological Association",
    description: "AUA annual meeting at the San Diego Convention Center."
  },
  {
    name: "EAU26 — 41st Annual Congress of the European Association of Urology",
    specialty: "Urology",
    year: 2026,
    startDate: "2026-03-13",
    endDate: "2026-03-16",
    city: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lng: -0.1278,
    url: "https://eaucongress.uroweb.org/",
    organizer: "European Association of Urology",
    description: "Europe's flagship annual urology congress at ExCeL London."
  },
  {
    name: "ASCRS Annual Scientific Meeting 2026",
    specialty: "Colorectal Surgery",
    year: 2026,
    startDate: "2026-05-09",
    endDate: "2026-05-12",
    city: "Tampa",
    country: "USA",
    lat: 27.9506,
    lng: -82.4572,
    url: "https://annualmeeting.ascrs.org/",
    organizer: "American Society of Colon and Rectal Surgeons",
    description: "Premier annual meeting of US colorectal surgeons at the Tampa Convention Center."
  },
  {
    name: "ASCRS Annual Scientific Meeting 2027",
    specialty: "Colorectal Surgery",
    year: 2027,
    startDate: "2027-04-02",
    endDate: "2027-04-05",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://annualmeeting.ascrs.org/",
    organizer: "American Society of Colon and Rectal Surgeons",
    description: "Annual scientific meeting of ASCRS."
  },
  {
    name: "ESCP 2026 — 21st Scientific Annual Meeting of the European Society of Coloproctology",
    specialty: "Colorectal Surgery",
    year: 2026,
    startDate: "2026-09-23",
    endDate: "2026-09-25",
    city: "Prague",
    country: "Czech Republic",
    lat: 50.0755,
    lng: 14.4378,
    url: "https://www.escp.eu.com/",
    organizer: "European Society of Coloproctology",
    description: "Europe's leading colorectal congress at the Prague Congress Centre."
  },
  {
    name: "AAST 85th Annual Meeting 2026",
    specialty: "Trauma Surgery",
    year: 2026,
    startDate: "2026-09-16",
    endDate: "2026-09-19",
    city: "Dallas",
    country: "USA",
    lat: 32.7767,
    lng: -96.7970,
    url: "https://www.aast.org/education/annual-meeting/past-and-future-meeting.html",
    organizer: "American Association for the Surgery of Trauma",
    description: "Premier trauma surgery meeting at the Hyatt Regency Dallas."
  },
  {
    name: "AAST 86th Annual Meeting 2027",
    specialty: "Trauma Surgery",
    year: 2027,
    startDate: "2027-09-15",
    endDate: "2027-09-18",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://www.aast.org/education/annual-meeting/past-and-future-meeting.html",
    organizer: "American Association for the Surgery of Trauma",
    description: "AAST annual meeting at the Hyatt Regency Chicago."
  },
  {
    name: "SSO 2026 Annual Meeting",
    specialty: "Surgical Oncology",
    year: 2026,
    startDate: "2026-03-05",
    endDate: "2026-03-07",
    city: "Phoenix",
    country: "USA",
    lat: 33.4484,
    lng: -112.0740,
    url: "https://surgonc.org/events/sso-annual-meeting/",
    organizer: "Society of Surgical Oncology",
    description: "SSO annual meeting at the Phoenix Convention Center."
  },
  {
    name: "SSO 2027 Annual Meeting",
    specialty: "Surgical Oncology",
    year: 2027,
    startDate: "2027-03-18",
    endDate: "2027-03-20",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://surgonc.org/events/sso-annual-meeting/",
    organizer: "Society of Surgical Oncology",
    description: "Annual meeting of the Society of Surgical Oncology."
  },
  {
    name: "APSA 2026 Annual Meeting",
    specialty: "Pediatric Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-09",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://apsapedsurg.org/continuing-education/events/annual-meeting/",
    organizer: "American Pediatric Surgical Association",
    description: "Premier US pediatric surgery meeting at the Sheraton Grand Chicago River Walk."
  },
  {
    name: "APSA 2027 Annual Meeting",
    specialty: "Pediatric Surgery",
    year: 2027,
    startDate: "2027-05-12",
    endDate: "2027-05-15",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://apsapedsurg.org/continuing-education/events/annual-meeting/",
    organizer: "American Pediatric Surgical Association",
    description: "APSA annual meeting at the Manchester Grand Hyatt San Diego."
  },
  {
    name: "IHPBA 2026 — 17th International Hepato-Pancreato-Biliary Association World Congress",
    specialty: "HPB / Transplant Surgery",
    year: 2026,
    startDate: "2026-10-28",
    endDate: "2026-10-31",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    url: "https://www.ihpba.org/19_world-congress.html",
    organizer: "International Hepato-Pancreato-Biliary Association",
    description: "Biennial world congress of HPB surgery at Suntec Singapore."
  },
  {
    name: "South Texas Chapter ACS 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-19",
    endDate: "2026-02-21",
    city: "Houston",
    country: "USA",
    lat: 29.7604,
    lng: -95.3698,
    url: "https://southtexasacs.org/2026-annual-meeting/",
    organizer: "South Texas Chapter, American College of Surgeons",
    description: "Annual meeting of the South Texas ACS chapter at The Westin Houston Medical Center."
  },
  {
    name: "ACS Florida Chapter 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-11",
    endDate: "2026-04-12",
    city: "Orlando",
    country: "USA",
    lat: 28.5384,
    lng: -81.3789,
    url: "https://www.floridafacs.org/2026-annual-meeting",
    organizer: "Florida Chapter, American College of Surgeons",
    description: "Florida Chapter annual meeting at the Orlando Health Jewett Orthopedic Institute, with the Copeland Research Symposium."
  },
  {
    name: "Missouri ACS 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    city: "Lake Ozark",
    country: "USA",
    lat: 38.1981,
    lng: -92.6346,
    url: "https://www.moacs.org/event-details/2026-annual-meeting",
    organizer: "Missouri Chapter, American College of Surgeons",
    description: "Missouri ACS chapter annual meeting at Camden on the Lake."
  },
  {
    name: "SC & NC ACS Joint Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    city: "Isle of Palms",
    country: "USA",
    lat: 32.7868,
    lng: -79.7842,
    url: "https://scfacs.org/",
    organizer: "South Carolina & North Carolina Chapters, American College of Surgeons",
    description: "Joint annual meeting of the SC and NC ACS chapters at Wild Dunes Resort."
  },
  {
    name: "Southern Surgical Association 138th Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-12-06",
    endDate: "2026-12-09",
    city: "Palm Beach",
    country: "USA",
    lat: 26.7056,
    lng: -80.0364,
    url: "https://southernsurg.org/meeting/",
    organizer: "Southern Surgical Association",
    description: "138th annual meeting of the Southern Surgical Association at The Breakers."
  },
  {
    name: "Southern Surgical Association 139th Annual Meeting",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-12-05",
    endDate: "2027-12-08",
    city: "Hot Springs",
    country: "USA",
    lat: 37.9971,
    lng: -79.8328,
    url: "https://southernsurg.org/meeting/Archives/",
    organizer: "Southern Surgical Association",
    description: "139th annual meeting at The Omni Homestead, Hot Springs, Virginia."
  },
  {
    name: "Pacific Coast Surgical Association 97th Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-04",
    endDate: "2026-02-08",
    city: "Ko Olina, Oahu",
    country: "USA",
    lat: 21.3370,
    lng: -158.1234,
    url: "https://www.pcsa2026.org/",
    organizer: "Pacific Coast Surgical Association",
    description: "Annual meeting of the PCSA at the Four Seasons Hotel Oahu at Ko Olina, Hawaii."
  },
  {
    name: "Southeastern Surgical Congress 2027 Annual Meeting",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-02-20",
    endDate: "2027-02-23",
    city: "Savannah",
    country: "USA",
    lat: 32.0809,
    lng: -81.0912,
    url: "https://sesc.org/annual-meeting/future-meetings",
    organizer: "Southeastern Surgical Congress",
    description: "SESC annual meeting at the Westin Savannah Harbor."
  },
  {
    name: "ACS Clinical Congress 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-10-16",
    endDate: "2027-10-19",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/future-clinical-congress/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons covering all surgical specialties."
  },
  {
    name: "ACS Clinical Congress 2028",
    specialty: "General Surgery",
    year: 2028,
    startDate: "2028-10-21",
    endDate: "2028-10-24",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/future-clinical-congress/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons covering all surgical specialties."
  },
  {
    name: "Kirurgveckan 2026 — Swedish Surgical Week",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    city: "Malmö",
    country: "Sweden",
    lat: 55.6050,
    lng: 13.0038,
    url: "https://www.kirurgveckan.se/",
    organizer: "Svensk Kirurgisk Förening (Swedish Surgical Society)",
    description: "Annual Swedish surgery week at Clarion Hotel & Congress Malmö Live — the flagship national gathering for Swedish surgeons."
  },
  {
    name: "Kirurgveckan 2027 — Swedish Surgical Week",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-08-23",
    endDate: "2027-08-27",
    city: "Gothenburg",
    country: "Sweden",
    lat: 57.7089,
    lng: 11.9746,
    url: "https://www.kirurgveckan.se/",
    organizer: "Svensk Kirurgisk Förening (Swedish Surgical Society)",
    description: "Annual Swedish surgery week held in Gothenburg (week 34; exact dates to be confirmed by organizers)."
  }
];
