// Edit this file to add or modify conferences.
// Each entry needs: name, specialty, year, startDate, endDate, city, country, lat, lng, url, organizer, description.
// Dates in YYYY-MM-DD format. Lat/lng are decimal degrees.

const CONFERENCES = [
  {
    name: "International Surgical Week (ISW 2026) — 51st World Congress of ISS/SIC",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-19",
    endDate: "2026-04-23",
    city: "Mexico City",
    country: "Mexico",
    lat: 19.4326,
    lng: -99.1332,
    url: "https://www.isw2026.org/",
    organizer: "International Society of Surgery (ISS/SIC)",
    description: "The 51st World Congress of the International Society of Surgery, the flagship global gathering for general surgeons."
  },
  {
    name: "ACS Clinical Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-26",
    endDate: "2026-09-29",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/clinical-congress-2026/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons, covering all surgical specialties."
  },
  {
    name: "European Surgery Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-17",
    endDate: "2026-08-19",
    city: "Paris",
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    url: "https://www.eurosurgerycongress.org/",
    organizer: "European Surgery Congress",
    description: "Major European general surgery congress."
  },
  {
    name: "34th International EAES Congress",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-23",
    endDate: "2026-06-26",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://eaes.eu/eaes-annual-congress/",
    organizer: "European Association for Endoscopic Surgery",
    description: "Annual congress focused on endoscopic, laparoscopic and minimally invasive surgery."
  },
  {
    name: "19th International Conference & Expo on Surgery and Surgeons",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-25",
    endDate: "2026-08-26",
    city: "Rome",
    country: "Italy",
    lat: 41.9028,
    lng: 12.4964,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "International conference covering advances across surgical specialties."
  },
  {
    name: "Global Conference on Surgery and Anaesthesia (7th Edition)",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-24",
    endDate: "2026-09-26",
    city: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lng: -0.1278,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "Hybrid international conference on surgery and anaesthesia."
  },
  {
    name: "Surgery 2026 — 4th International Conference on Surgery and Anesthesia",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-26",
    endDate: "2026-11-27",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://surgery-conferences.magnusgroup.org/",
    organizer: "Magnus Group",
    description: "Hybrid event covering surgical and anesthesia advances."
  },
  {
    name: "22nd Annual Academic Surgical Congress",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-02-09",
    endDate: "2027-02-11",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.academicsurgicalcongress.org/",
    organizer: "Association for Academic Surgery / Society of University Surgeons",
    description: "Joint annual academic surgery meeting featuring leading-edge surgical research."
  },
  {
    name: "EAES Annual Congress 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-06-15",
    endDate: "2027-06-18",
    city: "Düsseldorf",
    country: "Germany",
    lat: 51.2277,
    lng: 6.7735,
    url: "https://eaes.eu/eaes-annual-congress/",
    organizer: "European Association for Endoscopic Surgery",
    description: "Annual European endoscopic surgery congress."
  },
  {
    name: "62nd STS Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-01-30",
    endDate: "2026-02-02",
    city: "New Orleans",
    country: "USA",
    lat: 29.9511,
    lng: -90.0715,
    url: "https://www.sts.org/calendar-of-events/62nd-sts-annual-meeting",
    organizer: "Society of Thoracic Surgeons",
    description: "Premier meeting for cardiothoracic surgeons in North America."
  },
  {
    name: "AATS 106th Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-05-02",
    endDate: "2026-05-05",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://events.aats.org/am26",
    organizer: "American Association for Thoracic Surgery",
    description: "Flagship meeting of the AATS at McCormick Place, Chicago."
  },
  {
    name: "EACTS Annual Meeting 2026",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-10-07",
    endDate: "2026-10-10",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://www.eacts.org/",
    organizer: "European Association for Cardio-Thoracic Surgery",
    description: "Europe's leading cardiothoracic surgery congress."
  },
  {
    name: "34th ESTS Annual Meeting",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-06-07",
    endDate: "2026-06-09",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://estsmeeting.com/",
    organizer: "European Society of Thoracic Surgeons",
    description: "Annual meeting of the European Society of Thoracic Surgeons."
  },
  {
    name: "EACTS / STS / LACES Latin America Cardiovascular Surgery Conference",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-03-01",
    endDate: "2026-03-03",
    city: "Santiago",
    country: "Chile",
    lat: -33.4489,
    lng: -70.6693,
    url: "https://www.sts.org/calendar-of-events/2026-stseactslaces-latin-america-cardiovascular-surgery-conference",
    organizer: "EACTS / STS / LACES",
    description: "Joint Latin America cardiovascular surgery conference."
  },
  {
    name: "2026 CNS Annual Meeting",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-10-31",
    endDate: "2026-11-04",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.cns.org/annualmeeting",
    organizer: "Congress of Neurological Surgeons",
    description: "Premier annual meeting for neurosurgeons in the United States."
  },
  {
    name: "WFNS 5th International Neurosurgery and Neurological Surgeons Conference",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-01-14",
    endDate: "2026-01-16",
    city: "Dubai",
    country: "United Arab Emirates",
    lat: 25.2048,
    lng: 55.2708,
    url: "https://wfns.org/events/17/wfns-member-societies/329/5th-international-neurosurgery-and-neurological-surgeons-conference",
    organizer: "World Federation of Neurosurgical Societies",
    description: "International neurosurgery conference under WFNS member societies."
  },
  {
    name: "2027 CNS Annual Meeting",
    specialty: "Neurosurgery",
    year: 2027,
    startDate: "2027-10-23",
    endDate: "2027-10-27",
    city: "Phoenix",
    country: "USA",
    lat: 33.4484,
    lng: -112.0740,
    url: "https://www.cns.org/meetings/past-and-future-annual-meetings",
    organizer: "Congress of Neurological Surgeons",
    description: "Annual meeting of the Congress of Neurological Surgeons."
  },
  {
    name: "AANS 2027 Annual Scientific Meeting",
    specialty: "Neurosurgery",
    year: 2027,
    startDate: "2027-04-09",
    endDate: "2027-04-12",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://annualmeeting.aans.org/",
    organizer: "American Association of Neurological Surgeons",
    description: "Annual scientific meeting of the AANS."
  },
  {
    name: "AAOS 2026 Annual Meeting",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-03-02",
    endDate: "2026-03-06",
    city: "New Orleans",
    country: "USA",
    lat: 29.9511,
    lng: -90.0715,
    url: "https://aaos2026.org/",
    organizer: "American Academy of Orthopaedic Surgeons",
    description: "Largest orthopaedic surgery meeting in the world."
  },
  {
    name: "EFORT Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-05-04",
    endDate: "2026-05-06",
    city: "Málaga",
    country: "Spain",
    lat: 36.7213,
    lng: -4.4214,
    url: "https://www.efort.org/events-calendar/orthopaedic-event-calendar/",
    organizer: "European Federation of National Associations of Orthopaedics and Traumatology",
    description: "Annual European orthopaedics and traumatology congress."
  },
  {
    name: "SICOT 2026 Orthopaedic World Congress",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-09-29",
    endDate: "2026-10-01",
    city: "Kyoto",
    country: "Japan",
    lat: 35.0116,
    lng: 135.7681,
    url: "https://www.sicot.org/international-events-calendar",
    organizer: "Société Internationale de Chirurgie Orthopédique et de Traumatologie",
    description: "International orthopaedic and trauma surgery world congress."
  },
  {
    name: "Scoliosis Research Society Asia Pacific Meeting 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-02-06",
    endDate: "2026-02-07",
    city: "Fukuoka",
    country: "Japan",
    lat: 33.5902,
    lng: 130.4017,
    url: "https://www.srs.org/Meetings-Conferences/Regional-Scientific-Meeting/RSM-2026",
    organizer: "Scoliosis Research Society",
    description: "Regional meeting focused on spine deformity surgery."
  },
  {
    name: "ASPS Plastic Surgery The Meeting 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-10-15",
    endDate: "2026-10-18",
    city: "Houston",
    country: "USA",
    lat: 29.7604,
    lng: -95.3698,
    url: "https://www.plasticsurgerythemeeting.com/",
    organizer: "American Society of Plastic Surgeons",
    description: "Largest annual plastic surgery meeting in the United States."
  },
  {
    name: "ISAPS Body Masters 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-07-03",
    endDate: "2026-07-05",
    city: "Barcelona",
    country: "Spain",
    lat: 41.3851,
    lng: 2.1734,
    url: "https://www.isaps.org/education/events/events-calendar/",
    organizer: "International Society of Aesthetic Plastic Surgery",
    description: "International course on aesthetic body contouring surgery."
  },
  {
    name: "Aesthetic MEET 2026 (ASAPS)",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-05-14",
    endDate: "2026-05-17",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.theaestheticmeeting.com/",
    organizer: "American Society for Aesthetic Plastic Surgery",
    description: "Annual meeting of the Aesthetic Society."
  },
  {
    name: "2026 Asian Pacific Plastic Surgery & Craniofacial Congress",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-11-12",
    endDate: "2026-11-14",
    city: "Bangkok",
    country: "Thailand",
    lat: 13.7563,
    lng: 100.5018,
    url: "https://apc2026.org/",
    organizer: "Asian Pacific Plastic Surgery Association",
    description: "Regional Asia-Pacific congress for plastic and craniofacial surgery."
  },
  {
    name: "XXIX IFSO World Congress 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-09-01",
    endDate: "2026-09-04",
    city: "Toronto",
    country: "Canada",
    lat: 43.6532,
    lng: -79.3832,
    url: "https://ifso2026.org/",
    organizer: "International Federation for the Surgery of Obesity and Metabolic Disorders",
    description: "World congress on bariatric and metabolic surgery."
  },
  {
    name: "IFSO-EC Congress 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-08",
    city: "Málaga",
    country: "Spain",
    lat: 36.7213,
    lng: -4.4214,
    url: "https://www.ifso-ec.com/",
    organizer: "IFSO European Chapter",
    description: "European chapter congress on bariatric and metabolic surgery."
  },
  {
    name: "Joint IFSO-EC / EASO Congress 2027",
    specialty: "Bariatric Surgery",
    year: 2027,
    startDate: "2027-05-12",
    endDate: "2027-05-14",
    city: "Munich",
    country: "Germany",
    lat: 48.1351,
    lng: 11.5820,
    url: "https://www.ifso-ec.com/",
    organizer: "IFSO-EC / EASO",
    description: "Joint European bariatric / obesity congress."
  },
  {
    name: "APTS 2026 & SOHNSS ENT Congress",
    specialty: "Endocrine / ENT Surgery",
    year: 2026,
    startDate: "2026-04-09",
    endDate: "2026-04-12",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    url: "https://asean-endocrinejournal.org/index.php/JAFES/announcement/view/289",
    organizer: "Asia-Pacific Society of Thyroid Surgery",
    description: "Joint Asia-Pacific congress on thyroid and head & neck surgery."
  },
  {
    name: "Mayo Clinic Interactive Surgery Symposium 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-01",
    endDate: "2026-02-06",
    city: "Kapalua, Maui",
    country: "USA",
    lat: 20.9988,
    lng: -156.6678,
    url: "https://ce.mayo.edu/surgical-specialties/content/mayo-clinic-interactive-surgery-symposium-2026",
    organizer: "Mayo Clinic School of Continuous Professional Development",
    description: "General surgery CME symposium at The Ritz-Carlton Kapalua covering everyday surgical practice updates."
  },
  {
    name: "Mayo Clinic Advancements in Surgical & Medical Management of the Spine",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-02-22",
    endDate: "2026-02-26",
    city: "Lahaina, Maui",
    country: "USA",
    lat: 20.8783,
    lng: -156.6825,
    url: "https://ce.mayo.edu/",
    organizer: "Mayo Clinic School of Continuous Professional Development",
    description: "Spine surgery CME held at the Hyatt Regency Maui Resort and Spa, covering surgical and medical spine management."
  },
  {
    name: "Orthopedics Today Hawaii 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-01-10",
    endDate: "2027-01-14",
    city: "Wailea, Maui",
    country: "USA",
    lat: 20.6843,
    lng: -156.4416,
    url: "https://www.healio.com/meeting/othawaii/home",
    organizer: "Healio LIVE",
    description: "20th-anniversary orthopaedic CME conference at Grand Wailea covering sports medicine, arthroplasty, trauma, and practice management."
  },
  {
    name: "66th Annual Conference of the West African College of Surgeons (WACS)",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-08",
    endDate: "2026-02-12",
    city: "Accra",
    country: "Ghana",
    lat: 5.6037,
    lng: -0.1870,
    url: "https://66thwacs2026agsm.org/",
    organizer: "West African College of Surgeons",
    description: "Annual general meeting of WACS focused on building West African surgical capacity, held at the University of Professional Studies."
  },
  {
    name: "RACS 94th Annual Scientific Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-30",
    endDate: "2026-05-03",
    city: "Perth",
    country: "Australia",
    lat: -31.9523,
    lng: 115.8613,
    url: "https://www.surgeons.org/conferences-events/college-calendar-of-events/RACS-94th-Annual-Scientific-Congress-2026",
    organizer: "Royal Australasian College of Surgeons",
    description: "Annual scientific congress of the RACS at the Perth Convention and Exhibition Centre."
  },
  {
    name: "SVS Vascular Annual Meeting (VAM) 2026",
    specialty: "Vascular Surgery",
    year: 2026,
    startDate: "2026-06-10",
    endDate: "2026-06-13",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://vascular.org/vascular-specialists/education-and-meetings/meetings/2026-vascular-annual-meeting",
    organizer: "Society for Vascular Surgery",
    description: "Premier annual meeting for vascular surgeons in North America."
  },
  {
    name: "ESVS 40th Annual Meeting 2026",
    specialty: "Vascular Surgery",
    year: 2026,
    startDate: "2026-10-06",
    endDate: "2026-10-09",
    city: "Belgrade",
    country: "Serbia",
    lat: 44.7866,
    lng: 20.4489,
    url: "https://esvs.org/event/esvs-40th-annual-meeting/",
    organizer: "European Society for Vascular Surgery",
    description: "40th annual meeting of Europe's vascular surgery society."
  },
  {
    name: "XXVI Ibero-Latin American Congress of Plastic Surgery — FILACP Panama 2026",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-04-21",
    endDate: "2026-04-24",
    city: "Panama City",
    country: "Panama",
    lat: 8.9824,
    lng: -79.5199,
    url: "https://www.filacppanama2026.com/",
    organizer: "FILACP & Panamanian Association of Plastic, Aesthetic and Reconstructive Surgery",
    description: "Biennial Ibero-Latin American plastic surgery congress at the Panama Convention Center."
  },
  {
    name: "55° Congreso Argentino de Cirugía Plástica, Estética y Reparadora (SACPER)",
    specialty: "Plastic Surgery",
    year: 2026,
    startDate: "2026-10-21",
    endDate: "2026-10-23",
    city: "Rosario",
    country: "Argentina",
    lat: -32.9442,
    lng: -60.6505,
    url: "https://congresosacper2026.com/",
    organizer: "Sociedad Argentina de Cirugía Plástica (SACPER)",
    description: "55th Argentine congress of plastic, aesthetic and reconstructive surgery at City Center Rosario."
  },
  {
    name: "96° Congreso Argentino de Cirugía",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-02",
    endDate: "2026-11-04",
    city: "Buenos Aires",
    country: "Argentina",
    lat: -34.6037,
    lng: -58.3816,
    url: "https://aac.org.ar/96congreso/",
    organizer: "Asociación Argentina de Cirugía (AAC)",
    description: "Argentina's flagship surgery congress at Hotel Hilton Buenos Aires, alongside thoracic, coloproctology, plastic, trauma and breast sub-congresses."
  },
  {
    name: "L Congreso Internacional de Cirugía General (AMCG) 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-10-25",
    endDate: "2026-10-30",
    city: "Veracruz",
    country: "Mexico",
    lat: 19.1738,
    lng: -96.1342,
    url: "https://www.amcg2026.mx/",
    organizer: "Asociación Mexicana de Cirujanos Generales (AMCG)",
    description: "50th international congress of Mexican general surgeons, held at WTC Veracruz."
  },
  {
    name: "XXXII International Congress of Surgery — El Salvador 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-23",
    endDate: "2026-03-27",
    city: "San Salvador",
    country: "El Salvador",
    lat: 13.6929,
    lng: -89.2182,
    url: "https://congresocirugia2026.com/",
    organizer: "Asociación Salvadoreña de Cirugía General",
    description: "Salvadoran general surgery international congress at Hotel Hilton San Salvador, featuring 22 international speakers."
  },
  {
    name: "Endo 2026 — 5th World Congress of GI Endoscopy",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-24",
    endDate: "2026-09-26",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://www.surgeon.co.za/events/endo-2026-world-congress/",
    organizer: "Association of Surgeons of South Africa (ASSA)",
    description: "5th World Congress of GI Endoscopy hosted by ASSA in Cape Town."
  },
  {
    name: "SAOA 72nd Annual Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-08-31",
    endDate: "2026-09-03",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Orthopaedic Association (SAOA)",
    description: "Annual congress of the SAOA held at Century City, Cape Town."
  },
  {
    name: "27th SAAS Biennial Congress 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-08",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://arthroplastysociety.org.za/saas-congress-2026/",
    organizer: "South African Arthroplasty Society (SAAS)",
    description: "27th biennial congress of the South African Arthroplasty Society, focused on joint replacement surgery."
  },
  {
    name: "SAOA 73rd Annual Congress 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-09-06",
    endDate: "2027-09-09",
    city: "Cape Town",
    country: "South Africa",
    lat: -33.9249,
    lng: 18.4241,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Orthopaedic Association (SAOA)",
    description: "Annual SAOA congress in Century City, Cape Town."
  },
  {
    name: "SASS Spine Congress 2027",
    specialty: "Orthopedic Surgery",
    year: 2027,
    startDate: "2027-05-06",
    endDate: "2027-05-08",
    city: "Johannesburg",
    country: "South Africa",
    lat: -26.2041,
    lng: 28.0473,
    url: "https://saoa.org.za/local-events/",
    organizer: "South African Spine Society (SASS)",
    description: "Annual congress of the South African Spine Society at Sandton Convention Centre."
  },
  {
    name: "126th Annual Congress of the Japan Surgical Society",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-23",
    endDate: "2026-04-25",
    city: "Sapporo",
    country: "Japan",
    lat: 43.0642,
    lng: 141.3469,
    url: "https://jp.jssoc.or.jp/jss126/en/",
    organizer: "Japan Surgical Society (JSS)",
    description: "Japan's largest annual surgical congress, hosted by Hokkaido University."
  },
  {
    name: "127th Annual Congress of the Japan Surgical Society",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-04-08",
    endDate: "2027-04-10",
    city: "Tokyo",
    country: "Japan",
    lat: 35.6762,
    lng: 139.6503,
    url: "https://jp.jssoc.or.jp/modules/en/",
    organizer: "Japan Surgical Society (JSS)",
    description: "Annual congress of the Japan Surgical Society, hosted by Tokyo Medical University."
  },
  {
    name: "ASICON 2026 — 86th Annual Conference of the Association of Surgeons of India",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-12-17",
    endDate: "2026-12-19",
    city: "Ahmedabad",
    country: "India",
    lat: 23.0225,
    lng: 72.5714,
    url: "https://asicon26.com/",
    organizer: "Association of Surgeons of India (ASI)",
    description: "India's flagship surgical congress at the Gujarat University Convention & Exhibition Centre."
  },
  {
    name: "KSERS 2026 — 58th Korean Society of Endo-Laparoscopic & Robotic Surgery Congress",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-23",
    endDate: "2026-04-25",
    city: "Seoul",
    country: "South Korea",
    lat: 37.5665,
    lng: 126.9780,
    url: "https://ksers.org/",
    organizer: "Korean Society of Endo-Laparoscopic & Robotic Surgery",
    description: "Korean congress focused on endoscopic, laparoscopic, and robotic surgery."
  },
  {
    name: "AUA 2026 — 121st Annual Meeting of the American Urological Association",
    specialty: "Urology",
    year: 2026,
    startDate: "2026-05-15",
    endDate: "2026-05-18",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://www.auanet.org/AUA2026",
    organizer: "American Urological Association",
    description: "Largest annual urology meeting in North America, at Walter E. Washington Convention Center."
  },
  {
    name: "AUA 2027 — 122nd Annual Meeting of the American Urological Association",
    specialty: "Urology",
    year: 2027,
    startDate: "2027-05-21",
    endDate: "2027-05-24",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://www.auanet.org/AUA2027/for-exhibitors",
    organizer: "American Urological Association",
    description: "AUA annual meeting at the San Diego Convention Center."
  },
  {
    name: "EAU26 — 41st Annual Congress of the European Association of Urology",
    specialty: "Urology",
    year: 2026,
    startDate: "2026-03-13",
    endDate: "2026-03-16",
    city: "London",
    country: "United Kingdom",
    lat: 51.5074,
    lng: -0.1278,
    url: "https://eaucongress.uroweb.org/",
    organizer: "European Association of Urology",
    description: "Europe's flagship annual urology congress at ExCeL London."
  },
  {
    name: "ASCRS Annual Scientific Meeting 2026",
    specialty: "Colorectal Surgery",
    year: 2026,
    startDate: "2026-05-09",
    endDate: "2026-05-12",
    city: "Tampa",
    country: "USA",
    lat: 27.9506,
    lng: -82.4572,
    url: "https://annualmeeting.ascrs.org/",
    organizer: "American Society of Colon and Rectal Surgeons",
    description: "Premier annual meeting of US colorectal surgeons at the Tampa Convention Center."
  },
  {
    name: "ASCRS Annual Scientific Meeting 2027",
    specialty: "Colorectal Surgery",
    year: 2027,
    startDate: "2027-04-02",
    endDate: "2027-04-05",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://annualmeeting.ascrs.org/",
    organizer: "American Society of Colon and Rectal Surgeons",
    description: "Annual scientific meeting of ASCRS."
  },
  {
    name: "ESCP 2026 — 21st Scientific Annual Meeting of the European Society of Coloproctology",
    specialty: "Colorectal Surgery",
    year: 2026,
    startDate: "2026-09-23",
    endDate: "2026-09-25",
    city: "Prague",
    country: "Czech Republic",
    lat: 50.0755,
    lng: 14.4378,
    url: "https://www.escp.eu.com/",
    organizer: "European Society of Coloproctology",
    description: "Europe's leading colorectal congress at the Prague Congress Centre."
  },
  {
    name: "AAST 85th Annual Meeting 2026",
    specialty: "Trauma Surgery",
    year: 2026,
    startDate: "2026-09-16",
    endDate: "2026-09-19",
    city: "Dallas",
    country: "USA",
    lat: 32.7767,
    lng: -96.7970,
    url: "https://www.aast.org/education/annual-meeting/past-and-future-meeting.html",
    organizer: "American Association for the Surgery of Trauma",
    description: "Premier trauma surgery meeting at the Hyatt Regency Dallas."
  },
  {
    name: "AAST 86th Annual Meeting 2027",
    specialty: "Trauma Surgery",
    year: 2027,
    startDate: "2027-09-15",
    endDate: "2027-09-18",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://www.aast.org/education/annual-meeting/past-and-future-meeting.html",
    organizer: "American Association for the Surgery of Trauma",
    description: "AAST annual meeting at the Hyatt Regency Chicago."
  },
  {
    name: "SSO 2026 Annual Meeting",
    specialty: "Surgical Oncology",
    year: 2026,
    startDate: "2026-03-05",
    endDate: "2026-03-07",
    city: "Phoenix",
    country: "USA",
    lat: 33.4484,
    lng: -112.0740,
    url: "https://surgonc.org/events/sso-annual-meeting/",
    organizer: "Society of Surgical Oncology",
    description: "SSO annual meeting at the Phoenix Convention Center."
  },
  {
    name: "SSO 2027 Annual Meeting",
    specialty: "Surgical Oncology",
    year: 2027,
    startDate: "2027-03-18",
    endDate: "2027-03-20",
    city: "Washington, DC",
    country: "USA",
    lat: 38.9072,
    lng: -77.0369,
    url: "https://surgonc.org/events/sso-annual-meeting/",
    organizer: "Society of Surgical Oncology",
    description: "Annual meeting of the Society of Surgical Oncology."
  },
  {
    name: "APSA 2026 Annual Meeting",
    specialty: "Pediatric Surgery",
    year: 2026,
    startDate: "2026-05-06",
    endDate: "2026-05-09",
    city: "Chicago",
    country: "USA",
    lat: 41.8781,
    lng: -87.6298,
    url: "https://apsapedsurg.org/continuing-education/events/annual-meeting/",
    organizer: "American Pediatric Surgical Association",
    description: "Premier US pediatric surgery meeting at the Sheraton Grand Chicago River Walk."
  },
  {
    name: "APSA 2027 Annual Meeting",
    specialty: "Pediatric Surgery",
    year: 2027,
    startDate: "2027-05-12",
    endDate: "2027-05-15",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://apsapedsurg.org/continuing-education/events/annual-meeting/",
    organizer: "American Pediatric Surgical Association",
    description: "APSA annual meeting at the Manchester Grand Hyatt San Diego."
  },
  {
    name: "IHPBA 2026 — 17th International Hepato-Pancreato-Biliary Association World Congress",
    specialty: "HPB / Transplant Surgery",
    year: 2026,
    startDate: "2026-10-28",
    endDate: "2026-10-31",
    city: "Singapore",
    country: "Singapore",
    lat: 1.3521,
    lng: 103.8198,
    url: "https://www.ihpba.org/19_world-congress.html",
    organizer: "International Hepato-Pancreato-Biliary Association",
    description: "Biennial world congress of HPB surgery at Suntec Singapore."
  },
  {
    name: "South Texas Chapter ACS 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-19",
    endDate: "2026-02-21",
    city: "Houston",
    country: "USA",
    lat: 29.7604,
    lng: -95.3698,
    url: "https://southtexasacs.org/2026-annual-meeting/",
    organizer: "South Texas Chapter, American College of Surgeons",
    description: "Annual meeting of the South Texas ACS chapter at The Westin Houston Medical Center."
  },
  {
    name: "ACS Florida Chapter 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-11",
    endDate: "2026-04-12",
    city: "Orlando",
    country: "USA",
    lat: 28.5384,
    lng: -81.3789,
    url: "https://www.floridafacs.org/2026-annual-meeting",
    organizer: "Florida Chapter, American College of Surgeons",
    description: "Florida Chapter annual meeting at the Orlando Health Jewett Orthopedic Institute, with the Copeland Research Symposium."
  },
  {
    name: "Missouri ACS 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-18",
    endDate: "2026-04-19",
    city: "Lake Ozark",
    country: "USA",
    lat: 38.1981,
    lng: -92.6346,
    url: "https://www.moacs.org/event-details/2026-annual-meeting",
    organizer: "Missouri Chapter, American College of Surgeons",
    description: "Missouri ACS chapter annual meeting at Camden on the Lake."
  },
  {
    name: "SC & NC ACS Joint Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-14",
    endDate: "2026-08-16",
    city: "Isle of Palms",
    country: "USA",
    lat: 32.7868,
    lng: -79.7842,
    url: "https://scfacs.org/",
    organizer: "South Carolina & North Carolina Chapters, American College of Surgeons",
    description: "Joint annual meeting of the SC and NC ACS chapters at Wild Dunes Resort."
  },
  {
    name: "Southern Surgical Association 138th Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-12-06",
    endDate: "2026-12-09",
    city: "Palm Beach",
    country: "USA",
    lat: 26.7056,
    lng: -80.0364,
    url: "https://southernsurg.org/meeting/",
    organizer: "Southern Surgical Association",
    description: "138th annual meeting of the Southern Surgical Association at The Breakers."
  },
  {
    name: "Southern Surgical Association 139th Annual Meeting",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-12-05",
    endDate: "2027-12-08",
    city: "Hot Springs",
    country: "USA",
    lat: 37.9971,
    lng: -79.8328,
    url: "https://southernsurg.org/meeting/Archives/",
    organizer: "Southern Surgical Association",
    description: "139th annual meeting at The Omni Homestead, Hot Springs, Virginia."
  },
  {
    name: "Pacific Coast Surgical Association 97th Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-04",
    endDate: "2026-02-08",
    city: "Ko Olina, Oahu",
    country: "USA",
    lat: 21.3370,
    lng: -158.1234,
    url: "https://www.pcsa2026.org/",
    organizer: "Pacific Coast Surgical Association",
    description: "Annual meeting of the PCSA at the Four Seasons Hotel Oahu at Ko Olina, Hawaii."
  },
  {
    name: "Southeastern Surgical Congress 2027 Annual Meeting",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-02-20",
    endDate: "2027-02-23",
    city: "Savannah",
    country: "USA",
    lat: 32.0809,
    lng: -81.0912,
    url: "https://sesc.org/annual-meeting/future-meetings",
    organizer: "Southeastern Surgical Congress",
    description: "SESC annual meeting at the Westin Savannah Harbor."
  },
  {
    name: "ACS Clinical Congress 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-10-16",
    endDate: "2027-10-19",
    city: "San Diego",
    country: "USA",
    lat: 32.7157,
    lng: -117.1611,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/future-clinical-congress/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons covering all surgical specialties."
  },
  {
    name: "ACS Clinical Congress 2028",
    specialty: "General Surgery",
    year: 2028,
    startDate: "2028-10-21",
    endDate: "2028-10-24",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.facs.org/for-medical-professionals/conferences-and-meetings/future-clinical-congress/",
    organizer: "American College of Surgeons",
    description: "Annual flagship meeting of the American College of Surgeons covering all surgical specialties."
  },
  {
    name: "Kirurgveckan 2026 — Swedish Surgical Week",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-17",
    endDate: "2026-08-21",
    city: "Malmö",
    country: "Sweden",
    lat: 55.6050,
    lng: 13.0038,
    url: "https://www.kirurgveckan.se/",
    organizer: "Svensk Kirurgisk Förening (Swedish Surgical Society)",
    description: "Annual Swedish surgery week at Clarion Hotel & Congress Malmö Live — the flagship national gathering for Swedish surgeons."
  },
  {
    name: "Kirurgveckan 2027 — Swedish Surgical Week",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-08-23",
    endDate: "2027-08-27",
    city: "Gothenburg",
    country: "Sweden",
    lat: 57.7089,
    lng: 11.9746,
    url: "https://www.kirurgveckan.se/",
    organizer: "Svensk Kirurgisk Förening (Swedish Surgical Society)",
    description: "Annual Swedish surgery week held in Gothenburg (week 34; exact dates to be confirmed by organizers)."
  },
  {
    name: "ASGBI International Surgical Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    city: "Brighton",
    country: "United Kingdom",
    lat: 50.8225,
    lng: -0.1372,
    url: "https://www.asgbi.org.uk/",
    organizer: "Association of Surgeons of Great Britain and Ireland",
    description: "Flagship UK/Ireland general surgery congress at the Brighton Centre."
  },
  {
    name: "DCK 2026 — 143rd Deutscher Chirurgie Kongress",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-22",
    endDate: "2026-04-24",
    city: "Leipzig",
    country: "Germany",
    lat: 51.3397,
    lng: 12.3731,
    url: "https://www.dgch.de/",
    organizer: "Deutsche Gesellschaft für Chirurgie (DGCH)",
    description: "143rd annual congress of the German Surgical Society at the Congress Center Leipzig."
  },
  {
    name: "NVvH Chirurgendagen 2026 — Dutch Surgical Days",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-05-28",
    endDate: "2026-05-29",
    city: "Nieuwegein",
    country: "Netherlands",
    lat: 52.0333,
    lng: 5.0833,
    url: "https://congres.heelkunde.nl/",
    organizer: "Nederlandse Vereniging voor Heelkunde (NVvH)",
    description: "Annual spring congress of Dutch surgeons at NBC Nieuwegein. Theme: 'Voorbeeldig' (Exemplary)."
  },
  {
    name: "Swiss College of Surgeons Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-10",
    endDate: "2026-06-12",
    city: "Lucerne",
    country: "Switzerland",
    lat: 47.0502,
    lng: 8.3093,
    url: "https://scs-congress.ch/2026/",
    organizer: "Swiss College of Surgeons (SGC-SSC)",
    description: "Annual Swiss surgery congress at KKL Luzern, with a course day (June 10) and two congress days (June 11–12)."
  },
  {
    name: "128° Congresso Nazionale SIC 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-10-11",
    endDate: "2026-10-14",
    city: "Rome",
    country: "Italy",
    lat: 41.9028,
    lng: 12.4964,
    url: "https://sicroma2026.it/",
    organizer: "Società Italiana di Chirurgia (SIC)",
    description: "128th national congress of the Italian Society of Surgery at Ergife Palace Hotel, Rome."
  },
  {
    name: "27th Belgian Surgical Week 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-23",
    endDate: "2026-04-25",
    city: "Antwerp",
    country: "Belgium",
    lat: 51.2194,
    lng: 4.4025,
    url: "https://www.rbss.be/",
    organizer: "Royal Belgian Society for Surgery (RBSS)",
    description: "27th Belgian Surgical Week at Hilton Antwerp Old Town."
  },
  {
    name: "RCSI Charter Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-02-10",
    endDate: "2026-02-14",
    city: "Dublin",
    country: "Ireland",
    lat: 53.3498,
    lng: -6.2603,
    url: "https://www.rcsi.com/dublin/news-and-events/events/event/2026/charter-meeting-2026",
    organizer: "Royal College of Surgeons in Ireland",
    description: "Annual RCSI Charter Meeting at 123 St Stephen's Green. Theme: 'Progress and Precision'."
  },
  {
    name: "67th Austrian Chirurgenkongress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-17",
    endDate: "2026-06-19",
    city: "Salzburg",
    country: "Austria",
    lat: 47.8095,
    lng: 13.0550,
    url: "https://www.chirurgiekongress.at/",
    organizer: "Österreichische Gesellschaft für Chirurgie (ÖGCH)",
    description: "67th annual congress of the Austrian Surgical Society in Salzburg."
  },
  {
    name: "68th Austrian Chirurgenkongress 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-06-09",
    endDate: "2027-06-11",
    city: "Salzburg",
    country: "Austria",
    lat: 47.8095,
    lng: 13.0550,
    url: "https://oegch.at/",
    organizer: "Österreichische Gesellschaft für Chirurgie (ÖGCH)",
    description: "68th annual congress of the Austrian Surgical Society in Salzburg."
  },
  {
    name: "46º Congresso Nacional de Cirurgia SPCir 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-19",
    endDate: "2026-03-20",
    city: "Coimbra",
    country: "Portugal",
    lat: 40.2033,
    lng: -8.4103,
    url: "https://congresso.spcir.com/2026/",
    organizer: "Sociedade Portuguesa de Cirurgia (SPCir)",
    description: "46th National Congress of the Portuguese Surgical Society at Centro de Congressos de Coimbra."
  },
  {
    name: "DKS Årsmøde 2026 — Danish Surgical Society Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-12",
    endDate: "2026-11-13",
    city: "Copenhagen",
    country: "Denmark",
    lat: 55.6761,
    lng: 12.5683,
    url: "https://dks-arsmode.dk/",
    organizer: "Dansk Kirurgisk Selskab (DKS)",
    description: "Annual meeting of the Danish Surgical Society at The Hangar København."
  },
  {
    name: "NKF Høstmøtet 2026 — 101st Norwegian Surgical Autumn Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-10-19",
    endDate: "2026-10-23",
    city: "Oslo",
    country: "Norway",
    lat: 59.9139,
    lng: 10.7522,
    url: "https://hostmotet.no/",
    organizer: "Norsk Kirurgisk Forening (NKF)",
    description: "101st Norwegian Surgical Autumn Meeting — annual gathering organized jointly with eight specialty surgical societies."
  },
  {
    name: "Nordic-Baltic Bariatric Meeting 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-06-03",
    endDate: "2026-06-05",
    city: "Oslo",
    country: "Norway",
    lat: 59.9139,
    lng: 10.7522,
    url: "https://nbbm2026.no/",
    organizer: "Nordic-Baltic Bariatric collaboration",
    description: "Regional bariatric surgery meeting at Clarion Hotel Oslo."
  },
  {
    name: "24. Ulusal Cerrahi Kongresi 2026 (Turkish National Surgical Congress)",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-08",
    endDate: "2026-04-12",
    city: "Antalya",
    country: "Turkey",
    lat: 36.8969,
    lng: 30.7133,
    url: "https://uck2026.org/",
    organizer: "Türk Cerrahi Derneği (Turkish Surgical Society)",
    description: "24th Turkish National Surgical Congress and 19th National Surgical Nursing Congress at Titanic Convention Center."
  },
  {
    name: "10th Panhellenic Conference of Coloproctology 2026",
    specialty: "Colorectal Surgery",
    year: 2026,
    startDate: "2026-02-13",
    endDate: "2026-02-15",
    city: "Thessaloniki",
    country: "Greece",
    lat: 40.6401,
    lng: 22.9444,
    url: "https://coloproctology.gr/",
    organizer: "Hellenic Society of Coloproctology",
    description: "10th Panhellenic conference of the Hellenic Society of Coloproctology."
  },
  {
    name: "39th Panhellenic Congress of Neurosurgery 2026",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-06-11",
    endDate: "2026-06-14",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://www.thisisathens.org/acvb/news-global-events-upcoming-panhellenic-scientific-congresses-2026",
    organizer: "Hellenic Neurosurgical Society",
    description: "39th Panhellenic Neurosurgery Congress at the Royal Olympic Hotel, Athens."
  },
  {
    name: "82nd HSOST Congress 2026 — Hellenic Orthopaedic Surgery",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-10-14",
    endDate: "2026-10-17",
    city: "Athens",
    country: "Greece",
    lat: 37.9838,
    lng: 23.7275,
    url: "https://www.thisisathens.org/acvb/news-global-events-upcoming-panhellenic-scientific-congresses-2026",
    organizer: "Hellenic Society of Orthopaedic Surgery and Traumatology",
    description: "82nd congress of the Hellenic Society of Orthopaedic Surgery and Traumatology at Megaron Athens."
  },
  {
    name: "36º Congreso Nacional de Cirugía AEC 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-02",
    endDate: "2026-11-05",
    city: "Madrid",
    country: "Spain",
    lat: 40.4168,
    lng: -3.7038,
    url: "https://cncirugia2026.es/",
    organizer: "Asociación Española de Cirujanos (AEC)",
    description: "36th Spanish National Surgical Congress in Madrid. Theme: 'Sustainable excellence for the surgery of the future'."
  },
  {
    name: "RCSEd / CSHK Conjoint Scientific Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-14",
    endDate: "2026-11-14",
    city: "Hong Kong",
    country: "Hong Kong SAR",
    lat: 22.2480,
    lng: 114.1680,
    url: "https://csc.cshk.org/",
    organizer: "Royal College of Surgeons of Edinburgh & College of Surgeons of Hong Kong",
    description: "Conjoint scientific congress at the Hong Kong Academy of Medicine Jockey Club Building, Aberdeen."
  },
  {
    name: "PCS 82nd Annual Clinical Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-12-05",
    endDate: "2026-12-09",
    city: "Manila",
    country: "Philippines",
    lat: 14.5794,
    lng: 121.0359,
    url: "https://pcs.org.ph/",
    organizer: "Philippine College of Surgeons",
    description: "82nd Annual Clinical Congress at the EDSA Shangri-La Manila, Mandaluyong City."
  },
  {
    name: "CSAMM 52nd Annual Scientific Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-12",
    endDate: "2026-06-14",
    city: "Kuala Lumpur",
    country: "Malaysia",
    lat: 3.1390,
    lng: 101.6869,
    url: "https://csamm.org.my/",
    organizer: "College of Surgeons, Academy of Medicine of Malaysia",
    description: "52nd Annual Scientific Congress at Shangri-La Kuala Lumpur."
  },
  {
    name: "2026 TSA Annual Meeting & International Joint Surgical Conference",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-25",
    endDate: "2026-03-25",
    city: "Taipei",
    country: "Taiwan",
    lat: 25.0330,
    lng: 121.5654,
    url: "https://www.surgery.org.tw/en/",
    organizer: "Taiwan Surgical Association",
    description: "TSA annual meeting at the Taipei International Convention Center. Theme: 'Surgical Excellence for Healthy World'."
  },
  {
    name: "24th Caribbean College of Surgeons Annual Scientific Conference",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-07-01",
    endDate: "2026-07-04",
    city: "Scarborough, Tobago",
    country: "Trinidad and Tobago",
    lat: 11.1897,
    lng: -60.7392,
    url: "https://www.caribbeancollegeofsurgeons.com/24th-annual-scientific-conference/",
    organizer: "Caribbean College of Surgeons",
    description: "Annual scientific conference of the Caribbean College of Surgeons, rotating across the Caribbean — 2026 edition in Tobago."
  },
  {
    name: "43º Congreso Internacional de Cirugía — Colegio Dominicano de Cirujanos",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-07-02",
    endDate: "2026-07-05",
    city: "Punta Cana",
    country: "Dominican Republic",
    lat: 18.5601,
    lng: -68.3725,
    url: "https://cdc.org.do/",
    organizer: "Colegio Dominicano de Cirujanos (CDC)",
    description: "43rd international surgical congress of the Dominican College of Surgeons at the Hard Rock Punta Cana Convention Center."
  },
  {
    name: "XLVIII Congreso Nacional de Cirugía — Ecuador",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-05-20",
    endDate: "2026-05-22",
    city: "Guayaquil",
    country: "Ecuador",
    lat: -2.1710,
    lng: -79.9224,
    url: "https://www.dmccongresos.com/congresonacionaldecirugia",
    organizer: "Sociedad Ecuatoriana de Cirugía",
    description: "48th Ecuadorian national surgery congress at Hotel Hilton Colón, Guayaquil, with pre-congress courses May 19."
  },
  {
    name: "Surgical Society of Kenya Annual Scientific Conference 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-04-20",
    endDate: "2026-04-24",
    city: "Mombasa",
    country: "Kenya",
    lat: -4.0435,
    lng: 39.6682,
    url: "https://ssk.or.ke/",
    organizer: "Surgical Society of Kenya (SSK)",
    description: "Annual scientific conference at Pride Inn Hotel, Mombasa. Theme: 'From Policy to Patient: Transforming Surgical Access Across Africa'."
  },
  {
    name: "ISPN 2026 — 52nd Annual Meeting of the International Society for Pediatric Neurosurgery",
    specialty: "Neurosurgery",
    year: 2026,
    startDate: "2026-10-07",
    endDate: "2026-10-11",
    city: "Cairo",
    country: "Egypt",
    lat: 30.0444,
    lng: 31.2357,
    url: "https://www.ispnmeeting.org/",
    organizer: "International Society for Pediatric Neurosurgery",
    description: "52nd annual world meeting of pediatric neurosurgeons, hosted in Cairo."
  },
  {
    name: "EGSSO 21st Annual Conference 2026",
    specialty: "Surgical Oncology",
    year: 2026,
    startDate: "2026-05-07",
    endDate: "2026-05-08",
    city: "Cairo",
    country: "Egypt",
    lat: 30.0444,
    lng: 31.2357,
    url: "https://egsso.org.eg/",
    organizer: "Egyptian Society of Surgical Oncology",
    description: "21st annual conference of the Egyptian Society of Surgical Oncology at Tolip Gardens Hotel, Cairo."
  },
  {
    name: "ESLS 22nd International Congress 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-01-22",
    endDate: "2026-01-23",
    city: "Cairo",
    country: "Egypt",
    lat: 30.0444,
    lng: 31.2357,
    url: "https://eslscongress.com/",
    organizer: "Egyptian Society of Laparoscopic Surgery",
    description: "22nd international congress on laparoscopic and minimally invasive surgery at Hilton Cairo Grand Nile."
  },
  {
    name: "6th International Congress of the ACS UAE Chapter 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-11",
    endDate: "2026-09-12",
    city: "Dubai",
    country: "United Arab Emirates",
    lat: 25.2048,
    lng: 55.2708,
    url: "https://acscongressuae.com/",
    organizer: "American College of Surgeons — UAE Chapter",
    description: "6th international congress of the ACS UAE chapter in Dubai."
  },
  {
    name: "37º Congresso Brasileiro de Cirurgia (CBC 2027)",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-08-04",
    endDate: "2027-08-07",
    city: "Salvador",
    country: "Brazil",
    lat: -12.9714,
    lng: -38.5014,
    url: "https://cbc.org.br/congressos-brasileiros/",
    organizer: "Colégio Brasileiro de Cirurgiões (CBC)",
    description: "37th Brazilian Surgery Congress in Salvador, Bahia — Brazil's flagship biennial surgical meeting (3,000+ attendees)."
  },
  {
    name: "25º Congresso Paulista de Cirurgia 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-21",
    endDate: "2026-08-22",
    city: "São Paulo",
    country: "Brazil",
    lat: -23.5505,
    lng: -46.6333,
    url: "https://congressopaulistacbc.com.br/",
    organizer: "Colégio Brasileiro de Cirurgiões — Capítulo de São Paulo",
    description: "25th São Paulo state surgery congress at Centro de Convenções Rebouças."
  },
  {
    name: "XCVIII Congreso Chileno e Internacional de Cirugía 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-24",
    endDate: "2026-11-27",
    city: "La Serena",
    country: "Chile",
    lat: -29.9027,
    lng: -71.2519,
    url: "https://www.socich.cl/xcviii-congreso-chileno-e-internacional-de-cirugia/",
    organizer: "Sociedad Chilena de Cirugía",
    description: "98th Chilean and International Surgery Congress in La Serena."
  },
  {
    name: "XI Congreso Iberoamericano de Cirugía Pediátrica 2026",
    specialty: "Pediatric Surgery",
    year: 2026,
    startDate: "2026-09-01",
    endDate: "2026-09-04",
    city: "Santiago",
    country: "Chile",
    lat: -33.4489,
    lng: -70.6693,
    url: "https://aiacpchile2026.com/",
    organizer: "Asociación Iberoamericana de Cirugía Pediátrica",
    description: "11th Ibero-American pediatric surgery congress at the Sheraton Convention Center, Santiago."
  },
  {
    name: "SCGP Jornada Internacional de Cirugía General 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-11",
    endDate: "2026-03-13",
    city: "Lima",
    country: "Peru",
    lat: -12.0464,
    lng: -77.0428,
    url: "https://scgp.org/jornada-internacional-de-cirugia-general-2026/",
    organizer: "Sociedad de Cirujanos Generales del Perú / ACS Peru Chapter",
    description: "International general surgery days at the Sheraton Lima, held with the XX Congress of the ACS Peruvian chapter."
  },
  {
    name: "Mayo Clinic Interactive Surgery Symposium 2027",
    specialty: "General Surgery",
    year: 2027,
    startDate: "2027-01-31",
    endDate: "2027-02-05",
    city: "Waikoloa, Big Island",
    country: "USA",
    lat: 19.9172,
    lng: -155.8875,
    url: "https://ce.mayo.edu/surgical-specialties/content/mayo-clinic-interactive-surgery-symposium-2027",
    organizer: "Mayo Clinic School of Continuous Professional Development",
    description: "General surgery CME symposium at Hilton Waikoloa Village covering everyday surgical practice updates."
  },
  {
    name: "Western Trauma Association 55th Annual Meeting 2026",
    specialty: "Trauma Surgery",
    year: 2026,
    startDate: "2026-03-01",
    endDate: "2026-03-06",
    city: "Big Sky, Montana",
    country: "USA",
    lat: 45.2856,
    lng: -111.4014,
    url: "https://www.westerntrauma.org/annual-meeting/",
    organizer: "Western Trauma Association",
    description: "Annual ski-resort trauma surgery meeting at Big Sky Resort, Montana."
  },
  {
    name: "WTSA 52nd Annual Meeting 2026 — Western Thoracic Surgical Association",
    specialty: "Cardiothoracic Surgery",
    year: 2026,
    startDate: "2026-06-24",
    endDate: "2026-06-27",
    city: "Ivins, Utah",
    country: "USA",
    lat: 37.1683,
    lng: -113.6786,
    url: "https://westernthoracic.org/",
    organizer: "Western Thoracic Surgical Association",
    description: "52nd annual meeting of the WTSA at Black Desert Resort, southern Utah."
  },
  {
    name: "North Pacific Surgical Association Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-11-12",
    endDate: "2026-11-14",
    city: "Seattle, Washington",
    country: "USA",
    lat: 47.6062,
    lng: -122.3321,
    url: "https://www.northpacificsurgical.org/npsa-annual-meeting/",
    organizer: "North Pacific Surgical Association",
    description: "Pacific Northwest regional surgical meeting at the Lotte Hotel Seattle."
  },
  {
    name: "Mayfield Winter Clinics for Cranial & Spinal Surgery 2027",
    specialty: "Neurosurgery",
    year: 2027,
    startDate: "2027-02-28",
    endDate: "2027-03-04",
    city: "Snowmass Village, Colorado",
    country: "USA",
    lat: 39.2097,
    lng: -106.9378,
    url: "https://mayfieldfoundation.org/winterclinics/",
    organizer: "Mayfield Education & Research Foundation",
    description: "Ski-resort neurosurgery CME on cranial and spinal surgery at Viewline Snowmass."
  },
  {
    name: "UCSF Arthroplasty for the Modern Surgeon 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-08-28",
    endDate: "2026-08-29",
    city: "Napa, California",
    country: "USA",
    lat: 38.2975,
    lng: -122.2869,
    url: "https://orthosurgery.ucsf.edu/education/programs/ArthroplastyfortheModernSurgeon",
    organizer: "UCSF Department of Orthopaedic Surgery",
    description: "Joint replacement CME conference at Silverado Resort and Spa, Napa Valley."
  },
  {
    name: "UCSF Liver Transplant Symposium 2026",
    specialty: "HPB / Transplant Surgery",
    year: 2026,
    startDate: "2026-11-21",
    endDate: "2026-11-22",
    city: "Sonoma, California",
    country: "USA",
    lat: 38.2919,
    lng: -122.4580,
    url: "https://surgery.ucsf.edu/conferences-and-symposiums-0",
    organizer: "UCSF Department of Surgery",
    description: "Liver transplant and HPB surgery symposium in Sonoma, California."
  },
  {
    name: "Canadian Surgery Forum 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-16",
    endDate: "2026-09-19",
    city: "Halifax",
    country: "Canada",
    lat: 44.6488,
    lng: -63.5752,
    url: "https://www.canadiansurgeryforum.com/",
    organizer: "Canadian Association of General Surgeons and partners",
    description: "Canada's largest surgical meeting, at the Halifax Convention Centre, Nova Scotia."
  },
  {
    name: "COA 81st Annual Meeting 2026 — Canadian Orthopaedic Association",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-06-10",
    endDate: "2026-06-13",
    city: "St. John's",
    country: "Canada",
    lat: 47.5615,
    lng: -52.7126,
    url: "https://coa-aco.org/annual-meeting/",
    organizer: "Canadian Orthopaedic Association (COA/CORS/CORA)",
    description: "81st COA annual meeting at the St. John's Convention Centre, Newfoundland and Labrador."
  },
  {
    name: "New England Surgical Society 107th Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-09-18",
    endDate: "2026-09-20",
    city: "Uncasville, Connecticut",
    country: "USA",
    lat: 41.4362,
    lng: -72.0951,
    url: "https://nesurgical.org/",
    organizer: "New England Surgical Society",
    description: "107th annual meeting of the New England Surgical Society at Mohegan Sun, Connecticut."
  },
  {
    name: "Midwest Surgical Association Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-02",
    endDate: "2026-08-04",
    city: "Mackinac Island, Michigan",
    country: "USA",
    lat: 45.8492,
    lng: -84.6189,
    url: "https://midwestsurg.org/",
    organizer: "Midwest Surgical Association",
    description: "Annual meeting on Mackinac Island, Michigan — a classic destination surgical meeting."
  },
  {
    name: "SAGES 2026 Annual Meeting",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-03-25",
    endDate: "2026-03-28",
    city: "Tampa",
    country: "USA",
    lat: 27.9506,
    lng: -82.4572,
    url: "https://www.sages2026.org/",
    organizer: "Society of American Gastrointestinal and Endoscopic Surgeons (SAGES)",
    description: "Major meeting for minimally invasive, endoscopic, and robotic surgery at the Tampa Convention Center."
  },
  {
    name: "ASMBS Annual Meeting 2026",
    specialty: "Bariatric Surgery",
    year: 2026,
    startDate: "2026-05-03",
    endDate: "2026-05-07",
    city: "San Antonio",
    country: "USA",
    lat: 29.4241,
    lng: -98.4936,
    url: "https://asmbsmeeting.com/",
    organizer: "American Society for Metabolic and Bariatric Surgery (ASMBS)",
    description: "Annual meeting of the ASMBS, the premier US bariatric and metabolic surgery society."
  },
  {
    name: "Surfers Medical Association — Samoa 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-02-07",
    endDate: "2026-02-13",
    city: "Salani, Upolu",
    country: "Samoa",
    lat: -14.0170,
    lng: -171.5300,
    url: "https://surfersmedicalassociation.org/conferences/",
    organizer: "Surfers Medical Association",
    description: "Destination CME on ocean, surf, and wilderness medicine at Salani Surf Resort, Samoa."
  },
  {
    name: "Surfers Medical Association — Honolulu 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-03-05",
    endDate: "2026-03-07",
    city: "Honolulu, Hawaii",
    country: "USA",
    lat: 21.3069,
    lng: -157.8583,
    url: "https://surfersmedicalassociation.org/conferences/",
    organizer: "Surfers Medical Association",
    description: "Surf and ocean medicine CME conference in Honolulu."
  },
  {
    name: "Surfers Medical Association — Mag Bay, Mexico 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-08-01",
    endDate: "2026-08-08",
    city: "Magdalena Bay",
    country: "Mexico",
    lat: 24.6167,
    lng: -112.1000,
    url: "https://surfersmedicalassociation.org/conferences/",
    organizer: "Surfers Medical Association",
    description: "Week-long surf medicine CME at Magdalena Bay, Baja California Sur."
  },
  {
    name: "Surfers Medical Association — Nicaragua 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-09-03",
    endDate: "2026-09-10",
    city: "Pacific Coast",
    country: "Nicaragua",
    lat: 11.4500,
    lng: -86.1000,
    url: "https://surfersmedicalassociation.org/conferences/",
    organizer: "Surfers Medical Association",
    description: "Surf and wilderness medicine CME on Nicaragua's Pacific surf coast."
  },
  {
    name: "Surfers Medical Association — Portugal 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-10-10",
    endDate: "2026-10-17",
    city: "Ericeira",
    country: "Portugal",
    lat: 38.9631,
    lng: -9.4158,
    url: "https://surfersmedicalassociation.org/conferences/",
    organizer: "Surfers Medical Association",
    description: "Surf medicine CME conference on Portugal's Atlantic surf coast."
  },
  {
    name: "WMS Winter Conference 2026 — Wilderness Medical Society",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-02-22",
    endDate: "2026-02-25",
    city: "Incline Village, Lake Tahoe",
    country: "USA",
    lat: 39.2508,
    lng: -119.9462,
    url: "https://wms.org/",
    organizer: "Wilderness Medical Society",
    description: "Winter wilderness medicine CME at Hyatt Regency Lake Tahoe, Nevada."
  },
  {
    name: "International Extreme Sports Medicine Congress 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-06-05",
    endDate: "2026-06-06",
    city: "Park City, Utah",
    country: "USA",
    lat: 40.6461,
    lng: -111.4980,
    url: "https://medschool.cuanschutz.edu/orthopedics/clinical-services/sports-medicine/extreme-sports/international-extreme-sports-medicine-congress-2026",
    organizer: "University of Colorado / Extreme Sports Medicine",
    description: "Extreme and adventure sports medicine congress at Montage Deer Valley, Park City."
  },
  {
    name: "World Extreme Medicine Conference 2026",
    specialty: "Sports & Wilderness Medicine",
    year: 2026,
    startDate: "2026-11-14",
    endDate: "2026-11-16",
    city: "Edinburgh",
    country: "United Kingdom",
    lat: 55.9533,
    lng: -3.1883,
    url: "https://worldextrememedicine.com/world-extreme-medicine-conference/",
    organizer: "World Extreme Medicine",
    description: "Expedition, extreme, and humanitarian medicine conference at Dynamic Earth, Edinburgh."
  },
  {
    name: "ASSH 81st Annual Meeting 2026 — American Society for Surgery of the Hand",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-09-17",
    endDate: "2026-09-19",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.assh.org/annualmeeting",
    organizer: "American Society for Surgery of the Hand",
    description: "81st annual meeting of the ASSH, the premier US hand and upper extremity surgery society."
  },
  {
    name: "AAES Annual Meeting 2026 — American Association of Endocrine Surgeons",
    specialty: "Endocrine / ENT Surgery",
    year: 2026,
    startDate: "2026-04-18",
    endDate: "2026-04-20",
    city: "Lexington, Kentucky",
    country: "USA",
    lat: 38.0406,
    lng: -84.5037,
    url: "https://www.endocrinesurgery.org/2026-annual-meeting-home",
    organizer: "American Association of Endocrine Surgeons",
    description: "Annual meeting of the AAES, the leading US endocrine (thyroid, parathyroid, adrenal) surgery society."
  },
  {
    name: "American Hernia Society Annual Meeting 2026",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-08-27",
    endDate: "2026-08-29",
    city: "Denver",
    country: "USA",
    lat: 39.7392,
    lng: -104.9903,
    url: "https://www.americanherniasociety.org/meetings",
    organizer: "American Hernia Society",
    description: "Annual meeting focused on abdominal wall and hernia surgery at the Hyatt Regency Denver."
  },
  {
    name: "NASS 41st Annual Meeting 2026 — North American Spine Society",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-10-14",
    endDate: "2026-10-17",
    city: "San Antonio",
    country: "USA",
    lat: 29.4241,
    lng: -98.4936,
    url: "https://www.spine.org/AM",
    organizer: "North American Spine Society",
    description: "Multidisciplinary spine surgery convention at the Henry B. González Convention Center."
  },
  {
    name: "ICSES 2026 — International Congress of Shoulder and Elbow Surgery",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-09-22",
    endDate: "2026-09-25",
    city: "Vancouver",
    country: "Canada",
    lat: 49.2827,
    lng: -123.1207,
    url: "https://icses2026.org/",
    organizer: "International Congress of Shoulder and Elbow Surgery / ASES host",
    description: "Triennial world congress of shoulder and elbow surgery, hosted in Vancouver, BC."
  },
  {
    name: "AOFAS Annual Meeting & IFFAS 9th Biennial 2026",
    specialty: "Orthopedic Surgery",
    year: 2026,
    startDate: "2026-09-16",
    endDate: "2026-09-19",
    city: "Seattle, Washington",
    country: "USA",
    lat: 47.6062,
    lng: -122.3321,
    url: "https://www.aofas.org/annual-meeting",
    organizer: "American Orthopaedic Foot & Ankle Society / IFFAS",
    description: "Joint AOFAS annual meeting and IFFAS biennial world congress on foot and ankle surgery, Seattle."
  },
  {
    name: "American Transplant Congress 2026",
    specialty: "HPB / Transplant Surgery",
    year: 2026,
    startDate: "2026-06-20",
    endDate: "2026-06-24",
    city: "Boston",
    country: "USA",
    lat: 42.3601,
    lng: -71.0589,
    url: "https://www.atcmeeting.org/",
    organizer: "AST / ASTS (American Transplant Congress)",
    description: "The premier North American transplantation meeting, at the Westin Seaport Boston."
  },
  {
    name: "Mattox Vegas TCCACS 2027 — Trauma, Critical Care & Acute Care Surgery",
    specialty: "Trauma Surgery",
    year: 2027,
    startDate: "2027-03-15",
    endDate: "2027-03-17",
    city: "Las Vegas",
    country: "USA",
    lat: 36.1699,
    lng: -115.1398,
    url: "https://www.trauma-criticalcare.com/",
    organizer: "Mattox Vegas TCCACS",
    description: "The Mattox conference — annual trauma, critical care, and acute care surgery meeting at Caesars Palace, Las Vegas."
  },
  {
    name: "EHS Annual International Congress 2026 — European Hernia Society",
    specialty: "General Surgery",
    year: 2026,
    startDate: "2026-06-03",
    endDate: "2026-06-05",
    city: "Porto",
    country: "Portugal",
    lat: 41.1579,
    lng: -8.6291,
    url: "https://ehsporto2026.com/",
    organizer: "European Hernia Society",
    description: "EHS annual congress in Porto. Theme: 'Bridging the Future of Hernia Repair'."
  }
];
