  {
    name: "Internal Medicine for Primary Care: ID/Neuro/Rheum — Anaheim 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-04-23",
    endDate: "2027-04-25",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQzOQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Geri/ Palliative/Reproductive — Palm Beach 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-06-03",
    endDate: "2027-06-06",
    city: "Palm Beach",
    country: "Aruba",
    lat: 12.5735,
    lng: -70.0430,
    url: "https://www.mer.org/conference//MTQ1MA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Hyatt Regency Aruba Resort Spa & Casino, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Cardiology & Pulmonology for Primary Care — Anaheim 2027",
    specialty: "Cardiology",
    year: 2027,
    startDate: "2027-06-03",
    endDate: "2027-06-06",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQyNA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/ID/Pain/Rheum — San Juan 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-06-24",
    endDate: "2027-06-27",
    city: "San Juan",
    country: "Puerto Rico",
    lat: 18.4430,
    lng: -66.0170,
    url: "https://www.mer.org/conference//MTQ0MQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Royal Sonesta San Juan, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Neck & Spine/Ortho/Pod — Anaheim 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-07-02",
    endDate: "2027-07-04",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQyNQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Neurology & Psychiatry for Primary Care — Anaheim 2027",
    specialty: "Neurology",
    year: 2027,
    startDate: "2027-08-05",
    endDate: "2027-08-08",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQyNg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Cardiology & Pulmonology for Primary Care — Santa Fe 2027",
    specialty: "Cardiology",
    year: 2027,
    startDate: "2027-09-10",
    endDate: "2027-09-12",
    city: "Santa Fe",
    country: "USA",
    lat: 35.6870,
    lng: -105.9378,
    url: "https://www.mer.org/conference//MTQzOA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at La Fonda on the Plaza, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Endo/Palliative/Rheum — Estes Park 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-01",
    endDate: "2027-10-03",
    city: "Estes Park",
    country: "USA",
    lat: 40.3772,
    lng: -105.5217,
    url: "https://www.mer.org/conference//MTQ1MQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Holiday Inn Estes Park, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Addiction/ENT/Gyn — Napa 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-08",
    endDate: "2027-10-10",
    city: "Napa",
    country: "USA",
    lat: 38.2975,
    lng: -122.2869,
    url: "https://www.mer.org/conference//MTQ0OA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Napa Valley Marriott Hotel & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Geri/ID/Men's Uro — Lake Buena Vista 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-10",
    endDate: "2027-10-14",
    city: "Lake Buena Vista",
    country: "USA",
    lat: 28.3852,
    lng: -81.5639,
    url: "https://www.mer.org/conference//MTQyMg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Floridian Resort & Spa, offering 20 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Derm/Endo/Geri/Rheum — Poipu 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-10",
    endDate: "2027-10-14",
    city: "Poipu",
    country: "USA",
    lat: 21.8747,
    lng: -159.4540,
    url: "https://www.mer.org/conference//MTQyMw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Grand Hyatt Kauai Resort & Spa, offering 20 AMA PRA Category 1 Credits."
  },
  {
    name: "Cardiology & Pulmonology for Primary Care — Lake Buena Vista 2027",
    specialty: "Cardiology",
    year: 2027,
    startDate: "2027-10-15",
    endDate: "2027-10-17",
    city: "Lake Buena Vista",
    country: "USA",
    lat: 28.3852,
    lng: -81.5639,
    url: "https://www.mer.org/conference//MTQyNw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Floridian Resort & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Pediatric & Adolescent Medicine for Primary Care: Neuro/Ortho/Psych — Coronado 2027",
    specialty: "Pediatrics",
    year: 2027,
    startDate: "2027-10-15",
    endDate: "2027-10-17",
    city: "Coronado",
    country: "USA",
    lat: 32.6803,
    lng: -117.1783,
    url: "https://www.mer.org/conference//MTQyOA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Hotel del Coronado, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Geri/ID/Ortho — New York 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-15",
    endDate: "2027-10-17",
    city: "New York",
    country: "USA",
    lat: 40.7580,
    lng: -73.9855,
    url: "https://www.mer.org/conference//MTQ0Mg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at New York Marriott Marquis, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Gastro/Nephro/Pain/Rheum — Anaheim 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-21",
    endDate: "2027-10-24",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQyOQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Derm/Psych — Las Vegas 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-24",
    endDate: "2027-10-26",
    city: "Las Vegas",
    country: "USA",
    lat: 36.1147,
    lng: -115.1728,
    url: "https://www.mer.org/conference//MTQzMA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at The Cosmopolitan, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Endo/Gastro/Risk Mgmt — Charleston 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-29",
    endDate: "2027-10-31",
    city: "Charleston",
    country: "USA",
    lat: 32.7833,
    lng: -79.9333,
    url: "https://www.mer.org/conference//MTQzMQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Francis Marion Hotel, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Neck & Spine/Pod/Psych — New Orleans 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-29",
    endDate: "2027-10-31",
    city: "New Orleans",
    country: "USA",
    lat: 29.9511,
    lng: -90.0715,
    url: "https://www.mer.org/conference//MTQ0MA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at JW Marriott New Orleans, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Endo/Gastro/ Pulm/Reproductive — Wailea 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-10-31",
    endDate: "2027-11-04",
    city: "Wailea",
    country: "USA",
    lat: 20.6900,
    lng: -156.4420,
    url: "https://www.mer.org/conference//MTQzMg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Andaz Maui at Wailea Resort, offering 20 AMA PRA Category 1 Credits."
  },
  {
    name: "Neurology & Psychiatry for Primary Care — Lake Buena Vista 2027",
    specialty: "Neurology",
    year: 2027,
    startDate: "2027-11-04",
    endDate: "2027-11-07",
    city: "Lake Buena Vista",
    country: "USA",
    lat: 28.3852,
    lng: -81.5639,
    url: "https://www.mer.org/conference//MTQzMw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Yacht & Beach Club Resorts, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Endo/ID/Pulm — Phoenix 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-05",
    endDate: "2027-11-07",
    city: "Phoenix",
    country: "USA",
    lat: 33.4484,
    lng: -112.0740,
    url: "https://www.mer.org/conference//MTQzNA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Arizona Biltmore, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Gyn/Neuro/Sleep — Las Vegas 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-05",
    endDate: "2027-11-07",
    city: "Las Vegas",
    country: "USA",
    lat: 36.1147,
    lng: -115.1728,
    url: "https://www.mer.org/conference//MTQzNQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Caesars Palace, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Geri/Gyn/ID — Coronado 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-12",
    endDate: "2027-11-14",
    city: "Coronado",
    country: "USA",
    lat: 32.6803,
    lng: -117.1783,
    url: "https://www.mer.org/conference//MTQzNg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Hotel del Coronado, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Derm/Neuro/Ortho — Orlando 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-12",
    endDate: "2027-11-14",
    city: "Orlando",
    country: "USA",
    lat: 28.4740,
    lng: -81.4680,
    url: "https://www.mer.org/conference//MTQzNw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Loews Portofino Bay Hotel at Universal Orlando, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Gastro/Geri/Ortho/Rheum — Anaheim 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-18",
    endDate: "2027-11-21",
    city: "Anaheim",
    country: "USA",
    lat: 33.8085,
    lng: -117.9190,
    url: "https://www.mer.org/conference//MTQ0NA==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Californian Hotel & Spa, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Gastro/ID/Pulm — Key West 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-18",
    endDate: "2027-11-21",
    city: "Key West",
    country: "USA",
    lat: 24.5551,
    lng: -81.8000,
    url: "https://www.mer.org/conference//MTQ0NQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Casa Marina Key West, Curio Collection by Hilton, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Endo/Gyn/Psych — Lake Buena Vista 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-19",
    endDate: "2027-11-21",
    city: "Lake Buena Vista",
    country: "USA",
    lat: 28.3852,
    lng: -81.5639,
    url: "https://www.mer.org/conference//MTQ0Ng==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Floridian Resort & Spa, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Derm/Lifestyle — Scottsdale 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-11-19",
    endDate: "2027-11-21",
    city: "Scottsdale",
    country: "USA",
    lat: 33.4942,
    lng: -111.9261,
    url: "https://www.mer.org/conference//MTQ0OQ==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Hyatt Regency Resort and Spa at Gainey Ranch, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Cardiology & Pulmonology for Primary Care — Las Vegas 2027",
    specialty: "Cardiology",
    year: 2027,
    startDate: "2027-11-22",
    endDate: "2027-11-24",
    city: "Las Vegas",
    country: "USA",
    lat: 36.1147,
    lng: -115.1728,
    url: "https://www.mer.org/conference//MTQ0Nw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at The Venetian, offering 12 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Pod/Pulm/Rad — Lake Buena Vista 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-12-02",
    endDate: "2027-12-05",
    city: "Lake Buena Vista",
    country: "USA",
    lat: 28.3852,
    lng: -81.5639,
    url: "https://www.mer.org/conference//MTQ1Mg==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Disney's Grand Floridian Resort & Spa, offering 16 AMA PRA Category 1 Credits."
  },
  {
    name: "Internal Medicine for Primary Care: Cardio/Derm/Nephro/Palliative — Key West 2027",
    specialty: "Internal Medicine",
    year: 2027,
    startDate: "2027-12-02",
    endDate: "2027-12-05",
    city: "Key West",
    country: "USA",
    lat: 24.5551,
    lng: -81.8000,
    url: "https://www.mer.org/conference//MTQ1Mw==",
    organizer: "Medical Education Resources (MER)",
    description: "Destination primary care CME at Opal Key Resort & Marina, offering 16 AMA PRA Category 1 Credits."
  },
